### ISSUE TITLE
Editor Abilities - Call to API has Changed - Results in All Orgs being presented in Edit Mode

### ISSUE THREAD

**Issue by annikaLiving** [bcgov/ckan-ui#314] opened 2021-02-18 18:03 UTC
API Call has changed between versions.

**Comment by SteveChapmanBCDX** [comment] 2021-02-19 07:12
@annikaLiving - I'm not sure what the issue is here.  Is it that an editor who is modifying an existing record can add any organization or sub-organization to the record's "Organization" field?

**Comment by annikaLiving** [comment] 2021-02-19 15:15
@SteveChapmanBCDX  in our morning call, @BrandonSharratt found that the call to the API for an Editor had changed with the new version. I created the tix but do not know the exact wording.

Result is that the Editor profile is ignored and the entire list of orgs is presented. While as an Admin it is adhered to.

**Comment by SteveChapmanBCDX** [comment] 2021-02-19 19:54
@BrandonSharratt - I'm not sure what API call is being referenced here.  Is this a CKAN API call?

**Comment by BrandonSharratt** [comment] 2021-02-23 19:29
Yes this api call organization_list_for_user changed in ckan point versions. it used to want you to specify permission=editor but it no longer wants that it wants manage_group, read, create_dataset or unspecified (manage_group)

**Comment by SteveChapmanBCDX** [comment] 2021-02-24 17:40
@BrandonSharratt - I'm still seeing the same bug here.

Test #1 (DataBC editor):
* Added myself to KeyCloak `databc/editor` group
* Removed myself from `databc/admin` group
* Logged into Toyger
* Navigated to "Add Dataset" view
* Organization field contained all orgs (FAIL)

Test #2 (DataBC admin):
* Added myself to KeyCloak `databc/admin` group
* Removed myself from `databc/editor` group
* Logged into Toyger
* Navigated to "Add Dataset" view
* Organization field contained only "DataBC" (PASS)

**Comment by SteveChapmanBCDX** [comment] 2021-03-02 06:02
Tested in Toyger.  Fix implemented - closing ticket.

**Testing Summary:**

Test 1 (DataBC editor):

Added myself to KeyCloak databc/editor group
Removed myself from databc/admin group
Logged into Toyger
Navigated to "Add Dataset" view
Organization field contained only "DataBC" (PASS)

Test 2 (DataBC admin):

Added myself to KeyCloak databc/admin group
Removed myself from databc/editor group
Logged into Toyger
Navigated to "Add Dataset" view
Organization field contained only "DataBC" (PASS)

Test 3 (CKAN sysadmin):

Added myself to KeyCloak ckan/sysadmin group
Removed myself from databc/admin group
Logged into Toyger
Navigated to "Add Dataset" view
Organization field contained all organizations (PASS)

**Closed by SteveChapmanBCDX** 2021-03-02 06:02 UTC
Labels: High Priority, beta
