### ISSUE TITLE
When searching from header or landing page, the search terms are not persisting

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#302] opened 2021-02-18 00:34 UTC
Follow-up to #211, when searching from the header search, or the landing page, the search terms should persist in the search field of the Datasets view.
Steps to reproduce:

1. On the landing page, search for marmot.
2. The user is taken to the Datasets view.
3. The search term 'marmot' does not display on the search bar. The search term should be in the search bar so that the user knows that the search result being shown is the result of that search term.

**Comment by yuisotozaki** [comment] 2021-02-18 00:36
@SteveChapmanBCDX Can you reproduce this on your end?

**Comment by SteveChapmanBCDX** [comment] 2021-02-19 06:01
@yuisotozaki - I cannot reproduce from either the main landing page search bar or the header search.  In both instances, I was redirected to the datasets list page, where the term "marmot" was displayed in the search bar.  

I tested against version `1.9.0-85b4524`.

Closing the issue for now.  Can reopen if issue reappears.

**Closed by SteveChapmanBCDX** 2021-02-19 06:01 UTC
Labels: beta, consumer
