### ISSUE TITLE
Contact Types

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#156] opened 2020-07-23 22:40 UTC
**Story**
As an editor entering a record, I need to be able to communicate to DataBC the names and email addresses of key contacts type associated with the data type; Custodian (decision maker/owner), Editor, technical, Partner (GeoBC). This information should be supplied by the providing group and link to the functions that each contact type provides (e.g. answers technical questions, wants to receive notifications of errors, is owner of the data set/decision maker, provides technical support etc..)

**Design**
TBD

**Comment by BrandonSharratt** [comment] 2020-11-06 18:16
Is this still relevant?

**Comment by yuisotozaki** [comment] 2020-11-10 23:36
This should stay in the backlog as we venture into supporting better client engagement model in BCDC.

**Comment by sheilamv** [comment] 2020-11-11 01:13
This requirement is bringing in JIRA CRM information for Client Engagement which can be leveraged by multiple audiences.  

A **Custodian**, by definition, owns the data being provided and takes ownership of the metadata records and associated resources.  They are also the one who provides approval for any new editors being added to the Organization who is publishing the data.  This is a **required** role and should be enforced when an editor changes the state from **Draft** to **Pending Publish**.  This role should only be visible by logged in users who are Editors of the same organization or an Admin of the catalogue. 

An **Editor**, by definition is a **Data Manager** who has been delegated responsibilities by the **Custodian** to maintain the metadata records and its resources associated to the Organization.  It is not a metadata record role type but an access level granted to a user and defined in Keyclock.  This role is usually given to a _technical resource_ who works with technical resources supporting the DataBC Program. 

As noted above, a technical role is not defined at the metadata record level at this time.  A new contact role type could be created to address this requirement.  Like Business Expert, this role could be defined as **Technical Expert**.  

_Partner_, like GeoBC, is not role defined at the metadata record level.  They are usually Editors of the Organization to the metadata record is associated.  A new contact role type could be created to address this requirement.  Like Point of Contact, this role could be defined as **Partner**. 

There are two remaining contact role types that are used in the current catalogue:

- Point of Contact

- Business Expert

There may be overlap with what is noted above.  

|Current Roles on Metadata|SuggestedNew Roles|Comments|
|:---:|:---:|:---|
|Custodian|Custodian| Owner of data, not visible to any user except Admins and Editors of the organization|
| |Data Manager| Delegated owner of data - editor @ organization level, but specific to dataset, not visible to any user except Admins and Editors of the organization|
|Business Expert|Business Expert|Knows all about the data provided|
|Point of Contact|Technical Expert|Knows how to fix any technical issues around the data provided|
|Distributor|Distributor|Person(s) who manage the distribution of the data - DataBC is a distributor of BCA data|
| |Partner|A third party involved with the organization and its data|

I believe the **Display flag** should be fixed to be used as intended.  If **Checked** - displayed to users who are not logged in and **Unchecked** - invisible to users who are not logged in.  All contact roles but Custodian and Data Managers are invisible to logged in users, except Admins and Editors on the Organization (noted above).

**Closed by sheilamv** 2020-11-11 01:13 UTC
