### ISSUE TITLE
Unable to Edit Resources

### ISSUE THREAD

**Issue by annikaLiving** [bcgov/ckan-ui#340] opened 2021-02-24 03:09 UTC
Get an error when updating a resource. This has happened for tabular, Applications, WebServices and Geographic (has other issues i think related to https://github.com/bcgov/ckan-ui/issues/291)

**Unknown Error**
* Occasionally it spins for a second and does nothing.

Tried both with new resources and existing. 
* I tried to update the name
* Then one of the domain lists.
* This is for an existing webservice i tried to edit.
....dataset/geomark-web-service/resource/cdf4e0a6-de74-446e-a05c-37e3ea5a3b8f

Looking at the network dev tools. the following shows up when trying to save 

> error: {__type: "Validation Error"}
> help: "https://cati.data.gov.bc.ca/api/3/action/help_show?name=resource_update"
> success: false

Occasionally this error comes up with existing resources, like the OFI, WMS. Unsure if related

> There was an error while loading site ID 7535188336326689232. Please ensure the site ID is correct or contact your administrator.

**Comment by BrandonSharratt** [comment] 2021-03-01 17:33
https://github.com/bcgov/ckan-ui/pull/346

I have been unable to reproduce this issue after the recent schema change. but the above pr makes the error bar more visible.

**Comment by annikaLiving** [comment] 2021-03-02 19:07
Still receive an error editing a record.

Looking at the Dev Tools show 

> Status Code: 409

**Comment by SteveChapmanBCDX** [comment] 2021-03-03 07:05
See issue #345 - closing this ticket as duplicate.

**Closed by SteveChapmanBCDX** 2021-03-03 07:05 UTC
Labels: beta, editor
