### ISSUE TITLE
Group/Org Permalink not working

### ISSUE THREAD

**Issue by BrandonSharratt** [bcgov/ckan-ui#137] opened 2020-06-15 22:15 UTC
On a direct load or a page refresh the "Copy Permalink" for a group or individual org page doesn't work properly, as it has `undefined` for the id.

**Comment by SteveChapmanBCDX** [comment] 2020-08-25 22:25
@BrandonSharratt - It looks like this has been fixed.  Can you link to PR or commit?

**Comment by SteveChapmanBCDX** [comment] 2020-09-11 22:49
@BrandonSharratt  - I can still reproduce this issue in Toyger.  I don't think the code change has been committed.

**Comment by SteveChapmanBCDX** [comment] 2020-09-14 16:32
@BrandonSharratt  and I tested in Toyger.  Neither of us could reproduce this issue.  Closing as "cannot reproduce".

**Closed by SteveChapmanBCDX** 2020-09-14 16:32 UTC
